### ISSUE TITLE
Statblock won't import

### ISSUE THREAD

**Issue by esoneill** [Aioros/5e-statblock-importer#11]
Here is the text I am trying to use. The module threw a red error and told me to report it, which I did

`Large aberration, chaotic evil
Armor Class 18 (natural armor)
Hit Points 157 (15d10 + 75)
Speed 40 ft.
STR
DEX
CON
INT
WIS
CHA
20 (+5) 14 (+2) 20 (+5) 14 (+2) 16 (+3) 20 (+5)
Saving Throws Str +9, Con +9, Cha +9
Skills Arcana +10, Perception +7
Damage Immunities charmed, frightened, paralyzed
Senses truesight 30 ft., passive Perception 17
Languages all, telepathy 60 ft.
Challenge 9 (5,000 XP)
Aversion to Silence. If the horror is deafened at the start
of its turn, it takes 9 (2d8) psychic damage and has
disadvantage on all d20 tests until the start of its next turn.
Magic Resistance. The horror has advantage on saving
throws against spells and magical effects.
Actions
Multiattack. The horror makes three attacks.
Tentacle. Melee Weapon Attack: +9 to hit, reach 10 ft.,
one target. Hit: 10 (1d10 + 5) slashing damage. If the
target is Medium or smaller, it is grappled (escape DC 17).
While grappled, the target has disadvantage on Intelligence,
Wisdom, and Charisma saving throws. The horror has five
tentacles, each of which can grapple one creature.
Eldritch Blast. Ranged Spell Attack: +9 to hit, range 60 ft.,
one target. Hit: 10 (1d10 + 5) force damage.
Fracture Soul (Recharge 5–6). One creature the horror can
see within 30 feet must make a DC 17 Charisma saving
throw. On a failed save, the target takes 22 (5d8) psychic
damage and a copy of the target appears in an unoccupied
space within 5 feet of it. The copy has the target’s statistics,
except it is chaotic evil and has hit points equal to the psychic
damage dealt. The copy is under the horror’s control and
takes its turn immediately after the horror. The copy and its
equipment vanish after 1 minute or when it or the horror is
reduced to 0 hit points. On a successful save, the target takes
half damage.
Spellcasting. The horror’s spellcasting ability is Charisma
(spell save DC 17). It can innately cast the following spells,
requiring no material components:
1/day each: darkness, fear, hideous laughter (as a 5th-level spell)
Bonus Actions
Consume Spell. One creature the horror can see within
30 feet must make a DC 17 Constitution saving throw. On
a failed save, one spell of 5th level or lower ends on the
creature, and it takes 4 (1d8) force damage per level of the
spell. The horror gains temporary hit points equal to the
force damage dealt.
Eldritch Step. The horror teleports to an unoccupied space
it can see within 60 feet. Each creature within 20 feet of
where it appears must make a DC 17 Strength saving throw.
On a failed save, the creature takes 9 (2d8) force damage and
is pulled up to 15 feet toward the horror. On a successful
save, the creature takes half damage.
Reactions
Warp Spell. When a creature the horror can see within
60 feet casts a spell of 5th level or lower, the caster must
make a DC 17 saving throw using its spellcasting ability. On
a failed save, the horror can choose new targets for the spell
or a new target area. If the spell requires concentration, it
lasts until the end of the caster’s next turn, even if the caster
does not concentrate on it.`

**Comment by esoneill** [comment]
Investigation reveals it to be related to the Spellcasting block. I can move it to where the sample Glabrezu one is, but the spells themselves don't import for some reason.

**Comment by Aioros** [comment]
Hey, thanks for the report and sorry for the late reply. I just released v1.92.4 of the module, let me know if you still have the issue after updating the module.
