### ISSUE TITLE
Spellcasting actions from Monsters of the Multiverse format breaks importer

### ISSUE THREAD

**Issue by Airwrecker** [Aioros/5e-statblock-importer#12]
Hey Aioros,

A couple months ago I had brought up the issue where monster statblocks using the Spellcasting action format (which uses per day rather than spell slots) found Mordenkainen's Monsters of the Multiverse breaks the importer. I believe you had fixed it but it's breaking again:

An example is the Apprentice Wizard below:

Apprentice Wizard
Medium Humanoid, Any Alignment

Armor Class 10 (13 with mage armor)
Hit Points 13 (3d8)
Speed 30 ft.

STR
10 (+0)
DEX
10 (+0)
CON
10 (+0)
INT
14 (+2)
WIS
10 (+0)
CHA
11 (+0)

Skills Arcana +4, History +4
Senses Passive Perception 10
Languages any one language (usually Common)
Challenge 1/4 (50 XP)
Proficiency Bonus +2

Actions
Arcane Burst. Melee or Ranged Spell Attack: +4 to hit, reach 5 ft. or range 120 ft., one target. Hit: 7 (1d10 + 2) force damage.

Spellcasting. The apprentice casts one of the following spells, using Intelligence as the spellcasting ability (spell save DC 12):

At will: mage hand, prestidigitation

1/day each: burning hands, disguise self, mage armor

**Comment by summorme** [comment]
I had to change spellcasting to innate spellcasting in order to bypass the error

**Comment by Aioros** [comment]
Yep, sorry, I did apparently break it again when working on v4 compatibility. Should be working again in the latest version.

**Comment by Airwrecker** [comment]
@Aioros It works now! Thanks!
