### ISSUE TITLE
Statblock Importer Not Working Properly after 4.0.4

### ISSUE THREAD

**Issue by TombExplorer1997** [Aioros/5e-statblock-importer#3]
Hello the module is not working for since I updated to 4.0.4
Any Idea when the module is gonna be updated?
I use the classic Formating of Monster Statblocks and it seems to me that while basics stats are Imported without issue the actions are Imported without being automated.Like a breathweapon is on the statblock but not roll a save or area or damage.

**Comment by Aioros** [comment]
Yep, that's partly my bad for not setting the module compatibility to dnd5e 3.x only. I'll try to get actions to a reasonably working state soon.

**Comment by TombExplorer1997** [comment]
If I would have a wish it would really be great if the module accepts the old style of Statblock layout and the New one that is comming in the MM 2024 that we have previews for.

**Comment by Aioros** [comment]
Agreed, that is definitely next in line. It might take a while, though. You can open a new issue about it if you'd like, otherwise I probably will later on.

**Comment by TombExplorer1997** [comment]
Thank you very much.

**Comment by Aioros** [comment]
The latest release (v1.91.0) has much better compatibility with 4.x. Let me know if it solves your issues.

**Comment by TombExplorer1997** [comment]
It seems to solve most issues,one thing it does not automate is the AOE for things like breath weapons.Other than that it works for me.

**Comment by Aioros** [comment]
Ah, you're right, my bad. That should also be fixed now in v1.91.1.

**Comment by TombExplorer1997** [comment]
Works now.I will see If I find other problems.Thank you very much.
