### ISSUE TITLE
Actions are being imported as features

### ISSUE THREAD

**Issue by LeonZermeno** [Aioros/5e-statblock-importer#4]
Can't quite put it into more words than the title says, for some reason, some actions are imported into FoundryVTT as class/monster features. 
I took the Chuul statblock import as an example on the image below. Also as you may notice the attack itself scales with Dexterity rather than Strength, but that can be fixed by turning the attack from "Natural" to "Simple Melee".
![image](https://github.com/user-attachments/assets/31fe777b-ced5-4374-b5f3-fb7b693797b8)

**Comment by Aioros** [comment]
This should be fixed with the newly released v1.91.0. Let me know if that's the case after updating the module.

**Comment by LeonZermeno** [comment]
After some testing, it would seem the importer is working crispily again,
and everything is being imported properly, thank you very much for the
update
