### ISSUE TITLE
Import Stat Block Throwing An Error

### ISSUE THREAD

**Issue by OnegoodgreekDM** [Aioros/5e-statblock-importer#7]
Hi there I use Kenji's D&D  Monster Creator along with 5e Importer

This is what I was trying to import and got an error:

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/4f7f8344-7988-4354-8b28-a5d5499e5996">

here is the text:

Orra'Zal, Song of the Hunt
Medium humanoid (orc), neutral
Armor Class 14 (studied leather)
Hit Points 75 (10d10 + 20)
Speed 30 ft.
STR DEX CON INT WIS CHA
16 (+3) 14 (+2) 16 (+3) 10 (+0) 14 (+2) 8 (-1)
Saving Throws STR +6, DEX +5
Skills Survival +5, Stealth +5, Perception +5, Intimidation +2, Animal Handling +2
Damage Resistances Poison
Senses Darkvision 60 ft., passive Perception 15
Languages Orc, Common
Challenge 6 (2,300 XP)
Orcish Resilience. When reduced to 0 HP but not killed outright, Orra'Zal can drop to 1 HP instead.
Favored Enemy. Orra'Zal has advantage on Wisdom (Survival) checks to track cultists and aberrations, and on Intelligence checks to recall information about them.
Spellcasting. Orra'Zal's spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). She can innately cast the following spells: At will: Hunter’s Mark (bonus action), Pass Without Trace (concentration, 1 hour). 1/day each: Cure Wounds (touch, instantaneous), Absorb Elements (reaction, 1 round).
Actions
Multiattack. Orra'Zal makes four attacks: one with Bloodfang and three with her Gloomthorn Bow.
Bloodfang Slash. Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 9 (1d6 + 3) slashing damage. The target must make a DC 15 Constitution saving throw or be poisoned until the end of their next turn.
Gloomthorn Strike. Ranged Weapon Attack: +8 to hit, range 150 ft./600 ft., one target. Hit: 9 (1d8 + 2) piercing damage.
Hunting Shadow. Orra'Zal draws upon the power of her Gloomthorn Bow to create shadows that envelop her target. Ranged Spell Attack: +4 to hit, range 60 ft., one target. Hit: 12 (2d6 + 5) psychic damage. The target must succeed on a DC 15 Wisdom saving throw or become frightened until the end of their next turn. This ability recharges on a roll of 5 or 6 on a d6.

**Comment by Aioros** [comment]
In any case, it should work now in v1.91.3. Let me know if you still have the issue after updating the module.
