### ISSUE TITLE
Importing error - FIXED; thought I should share

### ISSUE THREAD

**Issue by N7Inquisitor** [Aioros/5e-statblock-importer#8]
Hey, I recently had an issue importing stat blocks with spellcasting. I had seen on some of the other threads that you had recommended changing the term "Spellcasting" to "Innate Spellcasting;" however, when I did that, the spellbook would not populate with the spells. It would remain blank. 

This was the following text: 
`Mage
Medium Humanoid (Any Race), Any Alignment

Armor Class 12 (15 with mage armor)
Hit Points 40 (9d8)
Speed 30 ft.

STR
9 (-1)
DEX
14 (+2)
CON
11 (+0)
INT
17 (+3)
WIS
12 (+1)
CHA
11 (+0)

Saving Throws INT +6, WIS +4
Skills Arcana +6, History +6
Senses Passive Perception 11
Languages Any four languages
Challenge 6 (2,300 XP)
Proficiency Bonus +3

Traits
Spellcasting. The mage is a 9th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 14, +6 to hit with spell attacks). The mage has the following wizard spells prepared:

Cantrips (at will): fire bolt, light, mage hand, prestidigitation

1st level (4 slots): detect magic, mage armor, magic missile, shield

2nd level (3 slots): misty step, suggestion

3rd level (3 slots): counterspell, fireball, fly

4th level (3 slots): greater invisibility, ice storm

5th level (1 slot): cone of cold

Actions
Dagger. Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage.`

However, for me, it seems that the issue was not the term "Spellcasting" as much as the term "Traits". I copy and pasted from D&D Beyond, so it technically put the spellcasting into the Traits section, but with your module, removing the line "Traits" fixed the issue.

**Comment by Aioros** [comment]
Very interesting, thanks. It looks like DDB (and others, as far as I can see) actually went through existing statblocks and updated them to include the "Traits" header. You can see that [it wasn't there before](https://web.archive.org/web/20240930094455/https://www.dndbeyond.com/monsters/16947-mage).

I'll have to fix that on my end. Thanks for the heads up!
