### ISSUE TITLE
Import button not showing

### ISSUE THREAD

**Issue by LazySwitch** [Aioros/5e-statblock-importer#9]
There is no option to import a stat block to Foundry anymore
[image](https://i.imgur.com/cdNXPKj.png)

**Comment by TheDailyDM** [comment]
Not a 'solution' to the core issue causing this but until this is fixed you can just use the manifest link of the previous version and the import button shows up as per usual. The error exists only in the 1.92 version and not in the 1.91.3 version.

**Comment by friction1** [comment]
I have the same issue

**Comment by Aioros** [comment]
Sorry for the inconvenience everyone, I'll try to find the issue. Can anyone confirm if they have any errors in the console?

**Comment by Aioros** [comment]
I would also love to know which browser and Foundry version, just in case it's something specific. I haven't been able to replicate the issue yet.

**Comment by Raixas** [comment]
I've found a workaround for now. The button will not appeaer within the app, however if you create a second user with full permissions, you can login using a browser and the browser version will show the button. I used firefox for this, my app version 12, buld 331 and 5e system 4.1.1.

**Comment by friction1** [comment]
> Sorry for the inconvenience everyone, I'll try to find the issue. Can anyone confirm if they have any errors in the console?

I do not see any errors when I load up and when I search for "importer" o
<img width="1068" alt="Screenshot 2024-11-17 at 8 48 40 AM" src="https://github.com/user-attachments/assets/d05de26b-daa1-4eeb-a1a0-16394c052e19">
r "stat" I don't see anything in the log related to this module.

I am just using the client, not a browser and its not showing up. 
<img width="293" alt="Screenshot 2024-11-17 at 8 49 00 AM" src="https://github.com/user-attachments/assets/dfaf2551-5bc1-477a-9074-ffaf39fa8600">

Also tried it with no other modules enabled.

**Comment by Aioros** [comment]
Thanks everyone, I was able to identify the issue. Updating to v1.92.1 should fix it, apologies again for the inconvenience.
